version: "3.9"
services:
  stac-api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: stac
      POSTGRES_PASSWORD: stac
      POSTGRES_DB: stac_db
    ports:
      - "5432:5432"
